<h1>Recherche de compte auditeur</h1>
<p>
    Bienvenue sur l'interface de recherche des comptes auditeurs.
</p>
<p>Cette interface vous permet de retrouver un compte auditeur à partir de son numéro de carte Grafic,
    son nom ou encore son adresse email personnelle</p>
<p>Pour pouvoir utiliser cette interface, vous devez être connecté(e). Pour vous connecter, utilisez vos paramètres VIRTUALIA.</p>
<p>Il faut également que votre compte soit autorisé. Si ce n'est pas le cas vous pouvez en faire la demande auprès de la DSI. </p>
