<br>

<?php if($this->initial) {?>
    Le mot de passe n'a pas été changé.<br><br>
<?php } else {?>
Le mot de passe a été changé. Si <?php echo $this->etudiant->getPrenom();?> <?php echo $this->etudiant->getNom();?> a perdu son mot de passe, vous pouvez le remettre à sa valeur d'origine
en cliquant sur <br><br/>
<?php }?>
<input id="sendMail" type="checkbox" name="sendMail"> Alerter l'élève par courriel<br/><br/>
<input type="hidden" id="sendMailHidden"/>
<a id="reinit" href="<?php echo $this->url(array("controller"=>"etudiant","action"=>"ajaxreinit","dn"=>$this->etudiant->getDn()),'default',true);?>">réinitialiser le mot de passe</a>
