<?php 
if(!$this->etudiants) { ?>
<h1>TEST SISCOL</h1>
<input type="hidden" id="url" value="<?php echo $this->url(array('controller'=>'etudiant','action'=>'listsiscoletudiants'));?>"/>
<input type="hidden" id="url2" value="<?php echo $this->url(array('controller'=>'etudiant','action'=>'siscoletudiant'));?>"/>
<input type="hidden" id="url3" value="<?php echo $this->url(array('controller'=>'etudiant','action'=>'ldapetudiant'));?>"/>
<table cellpadding="0" cellspacing="0" id="etudiants"></table>
    <?php echo $this->headScript()->appendFile($this->baseUrl('js/listsiscoletudiants.js','text/javascript')); ?>
<?php }
else { 
    $this->headScript()->appendFile($this->baseUrl('js/siscoletudiant.js','text/javascript'));
?>
    <?php foreach($this->etudiants as $etudiant) { 
        if(isset($etudiant->USERNAME)){ ?>

    <tr class="etudiant" id="<?php echo $etudiant->USERNAME;?>">
        <td><?php echo $etudiant->USERNAME;?></td>
    </tr>
    <?php }} ?>
<?php } ?>
