<?php echo $this->form; ?>
<?php if($this->etudiants) { ?>
<table cellpadding="0" cellspacing="0" style="font-size:10pt">
    <tr>
        <th>SAPID</th>
        <th>INE</th>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Date fin</th>
        <th>Email</th>
        <!--<th>Branche</th>-->
    </tr>
    <?php foreach($this->etudiants as $etudiant) { 
        if($etudiant->getStatutLdap()!="backup") { ?>
    <tr>
        <td><?php echo $etudiant->getSapid(); ?></td>
        <td><?php echo $etudiant->getIne(); ?></td>
        <td><?php echo $etudiant->getNom(); ?></td>
        <td><?php echo $etudiant->getPrenom(); ?></td>
        <td><?php echo $etudiant->getDatefin(); ?></td>
        <td><?php echo $etudiant->getEmail(); ?></td>
        <!--<td><?php //echo $etudiant->getStatutLdap(); ?></td>-->
    </tr>        
    <?php }} ?>
</table>    
<?php echo $this->bouton; ?>
<?php } ?>
