FROM php:5.3-apache
RUN apt-get -yq update
RUN apt-get install --force-yes -y git
 # Install needed php extensions: ldap
RUN \
    apt-get update && \
    apt-get install libldap2-dev -y && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap pdo pdo_mysql
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
RUN apt-get install -y openssl ssl-cert net-tools
WORKDIR /var/www/html/applications/siscolidentifiant/
ENV APPLICATION_ENV development
#COPY composer.phar /var/www/html/project/composer.phar
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
COPY default-ssl.conf /etc/apache2/sites-available/default-ssl.conf
#COPY ssl-cert-snakeoil.pem /etc/ssl/certs/ssl-cert-snakeoil.pem
#COPY ssl-cert-snakeoil.key /etc/ssl/private/ssl-cert-snakeoil.key
COPY index.php /var/www/html/index.php
RUN a2enmod rewrite
RUN a2enmod ssl
RUN a2ensite default-ssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/ssl-cert-snakeoil.key -out /etc/ssl/certs/ssl-cert-snakeoil.pem -subj "/C=AT/ST=Vienna/L=Vienna/O=Security/OU=Development/CN=example.com"

RUN chown -R www-data:www-data /var/www
RUN mkdir /fichiers
RUN chown www-data:www-data /fichiers
USER www-data:www-data
#COPY composer.json /var/www/html/project/composer.json
#RUN php /var/www/html/project/composer.phar install
EXPOSE 80
#EXPOSE 443